apiVersion: v1
kind: BuildConfig
metadata:
  name: webapp-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent any
          stages {
            stage('Build') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      openshift.startBuild("webapp").logs('-f')
                    }
                  }
                }
              }
            }
            stage('Deploy') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      dc = openshift.selector("dc", "webapp")
                      dc.rollout().latest()
                      timeout(10) {
                          dc.rollout().status("-w")
                      }
                    }
                  }
                }
              }
            }
            stage('Test') {
              steps {
                sh "curl -s http://webapp:8080/ | grep 'Hello'"
              }
            }
          }
        }
    type: JenkinsPipeline
